import { LitElement, html, css } from 'lit-element';

export class AuthErrorPage extends LitElement {
  constructor() {
    super();
    [this.loginButton] = document.getElementsByClassName('abcRioButton');
  }

  static get styles() {
    return css`
      :host {
        padding-top: 50px;
        width: 100vw;
        height: 100vh;
        display: grid;
        place-items: center;
      }

      #message-container {
        background-color: white;
        padding: 20px 50px;
        display: flex;
        flex-direction: column;
        align-items: center;
        min-width: 450px;
        width: 50%;
        max-width: 700px;
        height: 250px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2),
          0 6px 20px 0 rgba(0, 0, 0, 0.19);
      }

      #message-container p {
        flex: 1;
        text-align: center;
      }

      #message-container button {
        background-color: #fff;
        color: #757575;
        font-size: 13px;
        line-height: 34px;
        font-family: Roboto, arial, sans-serif;
        font-weight: 500;
        letter-spacing: 0.21px;

        border-radius: 20px;
        box-shadow: 0 2px 4px 0 rgb(0 0 0 / 25%);
        transition: border-color 0.218s, box-shadow 0.218s;
        box-sizing: border-box;
        color: #262626;
        cursor: pointer;
        border: 1px solid rgb(192, 189, 189);
        overflow: hidden;
        text-align: center;
        vertical-align: middle;
        white-space: nowrap;
        width: 240px;
        height: 46px;
      }

      #message-container button:hover {
        box-shadow: 0 0 3px 3px rgb(66 133 244 / 30%);
      }

      .scale-in-center {
        -webkit-animation: scale-in-center 0.5s
          cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
        animation: scale-in-center 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
          both;
      }

      /* ----------------------------------------------
 * Generated by Animista on 2021-5-18 16:23:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

      /**
 * ----------------------------------------
 * animation scale-in-center
 * ----------------------------------------
 */
      @-webkit-keyframes scale-in-center {
        0% {
          -webkit-transform: scale(0);
          transform: scale(0);
          opacity: 1;
        }
        100% {
          -webkit-transform: scale(1);
          transform: scale(1);
          opacity: 1;
        }
      }
      @keyframes scale-in-center {
        0% {
          -webkit-transform: scale(0);
          transform: scale(0);
          opacity: 1;
        }
        100% {
          -webkit-transform: scale(1);
          transform: scale(1);
          opacity: 1;
        }
      }
    `;
  }

  _handleLoginClick() {
    this.loginButton.click();
  }

  render() {
    return html`
      <main id="message-container" class="scale-in-center">
        <h1>Authentication Error</h1>
        <p>
          You need to be signed in with a valid google account if you want to
          access this content.
        </p>
        <button @click=${this._handleLoginClick} type="button">Sign in</button>
      </main>
    `;
  }
}

customElements.define('auth-error-page', AuthErrorPage);
